language: node_js
services:
  - docker
cache:
  directories:
    - ~/.npm
node_js:
  - '15'
git:
  depth: 3
script:
  - yarn install
  - yarn build
  - docker build . -t=react-native-expo-app:travis-build-$TRAVIS_BUILD_NUMBER
on:
  branch: develop 